export const GET_CONFIG = 'GET_CONFIG';
export const GET_GENRES = 'GET_GENRES';
export const SET_LOADING = 'SET_LOADING';
export const REMOVE_LOADING = 'REMOVE_LOADING';

// ERROR
export const INSERT_ERROR = 'INSERT_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

// SELCTED MENU
export const SET_SELECTED_MENU = 'SET_SELECTED_MENU';
export const REMOVE_SELECTED_MENU = 'REMOVE_SELECTED_MENU';
