export const GET_CONFIG = 'GET_CONFIG';
export const GET_GENRES = 'GET_GENRES';
export const SET_LOADING = 'SET_LOADING';
export const REMOVE_LOADING = 'REMOVE_LOADING';

// ERROR
export const INSERT_ERROR = 'INSERT_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

// SELCTED MENU
export const SET_SELECTED_MENU = 'SET_SELECTED_MENU';
export const REMOVE_SELECTED_MENU = 'REMOVE_SELECTED_MENU';

// movies
export const FETCH_MOVIES_LOADING = 'FETCH_MOVIES_LOADING';
export const FETCH_MOVIES_FINISHED = 'FETCH_MOVIES_FINISHED';
export const FETCH_MOVIES_DISCOVER = 'FETCH_MOVIES_DISCOVER';
export const FETCH_MOVIES_GENRES = 'FETCH_MOVIES_GENRES';
export const CLEAR_MOVIES = 'CLEAR_MOVIES';
